spring:
  application:
    name: open-finance-consent
  task:
    scheduling:
      enabled: true


  datasource:
    url: jdbc:postgresql://localhost:5432/openfinance
    username: openfinance
    password: openfinance123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    br.com.nevvesdev: DEBUG
    org.springframework.security: INFO

jobs:
    expire-consents:
      delay-ms: 60000
    outbox-relay:
      delay-ms: 30000

